#!/usr/bin/env bash
#This script will change user from root to nginx user and listen to port 8080
sed -i 's/www-data/nginx_user/g'  /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
