#!/usr/bin/env bash
#This script will change user from root to nginx user and listen to port 8080
echo 'user nginx;' > /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo service nginx restart
