#!/usr/bin/env bash
#Bash script to allow server respond to port 80
sed  "s/8080/80/g" /etc/nginx/sites-enabled/deflaut
#sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
service nginx restart

